= Main0
Invoke activemq jms operations as provided by activemq-examples openwire.
:TOC:


== SYNOPSIS

Invoke activemq jms operations as provided by activemq-examples openwire.

....
Main0 [-hV] [--jms-transacted]
    [--activemq-brokerURL=BROKER_URL]
    [--activemq-host=HOST]
    [--activemq-password=PASSWORD]
    [--activemq-port=PORT]
    [--activemq-user=USER]
    -c=<command>
    [--jms-deliverymode=<deliveryMode>]
    [--jms-queue=QUEUE]
    [--jms-timetolive=<timeToLive>]
    [--jms-topic=TOPIC]
    [--nummessages=<numMessages>]
....

== DESCRIPTION

....
Usage: Main0 [-hV] [--jms-transacted] [--activemq-brokerURL=BROKER_URL]
             [--activemq-host=HOST] [--activemq-password=PASSWORD]
             [--activemq-port=PORT] [--activemq-user=USER]
             -c=<command>
             [--jms-deliverymode=<deliveryMode>] [--jms-queue=QUEUE]
             [--jms-timetolive=<timeToLive>] [--jms-topic=TOPIC]
             [--nummessages=<numMessages>]
Invoke activemq jms operations as provided by activemq-examples openwire
      --activemq-brokerURL=BROKER_URL
                             activemq brokerURL
                               Default: tcp://localhost:61616
      --activemq-host=HOST   activemq host
                               Default: localhost
      --activemq-password=PASSWORD
                             activemq password
                               Default: password
      --activemq-port=PORT   activemq port
                               Default: 61616
      --activemq-user=USER   activemq user
                               Default: admin
  -c, --command=<command>    launch a command; valid values: queueProducer,
                               queueConsumer, advisory, topicPublisher,
                               topicSubscriber, durSubPublisher,
                               durSubSubscriber, browser, browserProducer,
                               tempDestConsumer, tempDestProducerRequestReply
  -h, --help                 Show this help message and exit.
      --jms-deliverymode=<deliveryMode>
                             jms delivery mode [PERSISTENT|NON_PERSISTENT]
                               Default: NON_PERSISTENT
      --jms-queue=QUEUE      jms destination queue
                               Default: test-queue
      --jms-timetolive=<timeToLive>
                             jms timetolive [ms]
                               Default: 60000
      --jms-topic=TOPIC      jms destination topic
                               Default: test-topic
      --jms-transacted       jms transacted
      --nummessages=<numMessages>
                             count of messages to produce
                               Default: 100
  -V, --version              Print version information and exit.
....

== Supported Command

Following command are supported:

[cols=2*]
|===
| Command                        | Description
| queueProducer                  | send messages into a queue
| queueConsumer                  | receive messages from a queue
| advisory                       | receive advisory messages
| topicPublisher                 | send message into a topic
| topicSubscriber                | receive messages from a topic
| durSubPublisher                | send messges into a topic
| durSubSubscriber               | receive messages from a topic as durable subscriber
| browser                        | browse messages from a queue
| browserProducer                | send messages into a queue
| tempDestConsumer               | temporary queue consumer 
| tempDestProducerRequestReply   | temporary queue producer
|===

== Example queueProducer

Send 5 messages to the queue test-queue,
 at url: tcp://localhost:61616,
 using user/password admin/password
.

....
$ $JAVA_HOME/bin/java -jar target/jms-example-picocli-0.1-SNAPSHOT-main0.jar --command=queueProducer --nummessages=5
[main] INFO org.huberb.apacheactivemq.examples.picocli.Main0 - Parameters:
command queueProducer, user admin, password password, brokerURL tcp://localhost:61616, host localhost, port 61616, queue test-queue, topic test-topic, transacted false, deliveryMode NON_PERSISTENT, timeToLive 60000, numMessages 5
[main] INFO example.queue.Producer - Running with:
url: tcp://localhost:61616,
user: admin, [ACTIVEMQ_USER]
password: password, [ACTIVEMQ_PASSWORD]
host: localhost, [ACTIVEMQ_HOST]
port: 61616, [ACTIVEMQ_PORT]
queue: test-queue, [QUEUE]
transacted: false, [TRANSACTED]
deliveryMode: 1 (PERSISTENT 2, NON_PERSISTENT 1), [DELIVERY_MODE]
timeToLive: 60000 ms [TIME_TO_LIVE]
numMessages: 5 [NUM_MESSAGES]
[main] INFO example.queue.Producer - Sending message #0
[main] INFO example.queue.Producer - Sending message #1
[main] INFO example.queue.Producer - Sending message #2
[main] INFO example.queue.Producer - Sending message #3
[main] INFO example.queue.Producer - Sending message #4
....

== Example queueConsumer

Receive messages from the queue test-queue,
 at url: tcp://localhost:61616,
 using user/password admin/password
.

....
$ $JAVA_HOME/bin/java -jar target/jms-example-picocli-0.1-SNAPSHOT-main0.jar --command=queueConsumer
[main] INFO org.huberb.apacheactivemq.examples.picocli.Main0 - Parameters:
command queueConsumer, user admin, password password, brokerURL tcp://localhost:61616, host localhost, port 61616, queue test-queue, topic test-topic, transacted false, deliveryMode NON_PERSISTENT, timeToLive 60000, numMessages 100
[main] INFO example.queue.Consumer - Running with:
url: tcp://localhost:61616,
user: admin, [ACTIVEMQ_USER]
password: password, [ACTIVEMQ_PASSWORD]
host: localhost, [ACTIVEMQ_HOST]
port: 61616, [ACTIVEMQ_PORT]
queue: test-queue, [QUEUE]
transacted: false, [TRANSACTED]

[main] INFO example.queue.Consumer - Waiting to receive messages... will timeout after 20s
[main] INFO example.queue.Consumer - Got #0  message: Message #0
[main] INFO example.queue.Consumer - Got #1  message: Message #1
[main] INFO example.queue.Consumer - Got #2  message: Message #2
[main] INFO example.queue.Consumer - Got #3  message: Message #3
[main] INFO example.queue.Consumer - Got #4  message: Message #4
....

