= Main0
Invoke activemq jms operations as provided by activemq-examples openwire.
:TOC:


== SYNOPSIS

Invoke activemq jms operations as provided by activemq-examples openwire.

....
Main0 [-hV] [--jms-transacted]
    [--activemq-brokerURL=BROKER_URL]
    [--activemq-host=HOST]
    [--activemq-password=PASSWORD]
    [--activemq-port=PORT]
    [--activemq-user=USER]
    -c=<command>
    [--jms-deliverymode=<deliveryMode>]
    [--jms-queue=QUEUE]
    [--jms-timetolive=<timeToLive>]
    [--jms-topic=TOPIC]
    [--nummessages=<numMessages>]
....

== DESCRIPTION

....
Usage: Main0 [-hV] [--jms-transacted] [--activemq-brokerURL=BROKER_URL]
             [--activemq-host=HOST] [--activemq-password=PASSWORD]
             [--activemq-port=PORT] [--activemq-user=USER] 
             -c=<command>
             [--jms-deliverymode=<deliveryMode>] [--jms-queue=QUEUE]
             [--jms-timetolive=<timeToLive>] [--jms-topic=TOPIC]
             [--nummessages=<numMessages>]
Invoke activemq jms operations as provided by activemq-examples openwire
      --activemq-brokerURL=BROKER_URL
                             activemq brokerURL
                               Default: tcp://localhost:61616
      --activemq-host=HOST   activemq host
                               Default: localhost
      --activemq-password=PASSWORD
                             activemq password
                               Default: password
      --activemq-port=PORT   activemq port
                               Default: 61616
      --activemq-user=USER   activemq user
                               Default: admin
  -c, --command=<command>    launch a command; valid values: queueProducer,
                               queueConsumer, advisory, topicPublisher,
                               topicSubscriber, durSubPublisher,
                               durSubSubscriber, browser, browserProducer,
                               tempDestConsumer, tempDestProducerRequestReply
  -h, --help                 Show this help message and exit.
      --jms-deliverymode=<deliveryMode>
                             jms delivery mode [PERSISTENT|NON_PERSISTENT]
                               Default: NON_PERSISTENT
      --jms-queue=QUEUE      jms destination queue
                               Default: test-queue
      --jms-timetolive=<timeToLive>
                             jms timetolive [ms]
                               Default: 60000
      --jms-topic=TOPIC      jms destination topic
                               Default: test-topic
      --jms-transacted       jms transacted
      --nummessages=<numMessages>
                             count of messages to produce
                               Default: 100
  -V, --version              Print version information and exit.
....
